name: e_comm_new
description: Migrated e-commerce app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  dartz: ^0.10.1
  fluttertoast: ^9.0.0
  shared_preferences: ^2.5.4
  cached_network_image: ^3.4.1
  carousel_slider_plus: ^7.0.1
  flutter_slidable: ^3.1.1
  auto_size_text: ^3.0.0
  colornames: ^0.1.0
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.1
  readmore: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  get_it: ^9.2.0
  injectable: ^2.7.1+4
  injectable_generator: ^2.11.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.10.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-.ttf
